### ISSUE TITLE
 DISTRE precision.npy and recall.npy

### ISSUE THREAD

**Issue by kingsunfather** [DespinaChristou/REDSandT#1]
Hello, can you upload the precision.npy and recall.npy files of the DISTRE model in the NYT10 dataset? My hardware resources are not enough to run the DISTRE model, but I want to compare my model with the DISTRE pr curve. Hope to get your help, thank you very much!

**Comment by DespinaChristou** [comment]
Hello! Please check section 'Baselines' in the README.md file. You can find the precision and recall values of all baseline models in the provided link. Thanks for your interest.
